### PR TITLE
Working for Turkish translation

### PR DESCRIPTION
**Pull request by goeksu**
Hello!
As a developer in your Turkish community, I retranslated your whitepaper in more better way.

### CODE REVIEW

**Comment by lesterli** [comment]
Hey, firstly thanks for your translation.
I downloaded your translation file ([Whitepaper - Turkish.pdf](https://github.com/goeksu/papers/blob/main/languages/Whitepaper%20-%20Turkish.pdf)), but it can't be opened. I got the error message: it seems file was borken.
Could you please check it and upload it again?

**Comment by goeksu** [comment]
Hello,
I think it is fixed now!

**Comment by lesterli** [comment]
yes, we will review it.

**Comment by en** [comment]
@goeksu Thank you for your contribution.

Bugra Ayan from Web3 Foundation Turkey helped us review the translation.
He has made some comments in the pdf. Could you update this PR with his advice?
 
[Whitepaper - Turkish.pdf](https://github.com/octopus-network/papers/files/13320824/Whitepaper.-.Turkish.pdf)

**Comment by goeksu** [comment]
sorry for delay, i have reviewed the highlighted lines.

**Comment by en** [comment]
Thank you!

**Comment by goeksu** [comment]
welcome!

**Pull request merged**
